---
title: "**Revue de littérature : L'effet de TikTok sur les élections présidentielles de Roumanie 2024**"
output: 
  html_document:
    toc: true
    toc_float: true
date: "2025-12-23"
---

**Chiara Motard - 04/12/2025**  

**Thématique : L’effet de TikTok sur les élections présidentielles de Roumanie en novembre 2024**  



La désinformation massive sur les réseaux sociaux (provoquée par des réseaux russes), notamment sur Tik Tok, conduisant à la victoire du candidat populiste d’extrême-droite pro russe Câlin Georgescu a conduit à l’annulation, par la Cour suprême, du premier tour de l’élection présidentielle roumaine en novembre 20241. En ce sens, le Monde évoque « de graves manipulations sur TikTok » 2. Si les manipulations électorales sur les réseaux sociaux ont été identifiées lors de l'élection présidentielle de 2016 aux Etats-Unis (Allcott, H., & Gentzkow, M. (2017)), elles se sont accentuées depuis le début de la guerre en Ukraine, dans le cadre de la « guerre hybride». En effet, les ingérences numériques russes se sont décuplées lors des dernières élections en Europe notamment en Roumanie. Călin Georgescu a obtenu un nombre important de voix grâce à une stratégie de manipulation de l'information3.  
Quel est l'effet du réseau social TikTok sur les résultats du premier tour des élections roumaines en novembre 2024, conduisant à la victoire de Câlin Georgescu ? 
Ce sujet pose une pluralité de questions, dont l’impact des réseaux sociaux sur les comportements électoraux. L’intérêt de ce sujet est dual, tant par sa dimension démocratique qu’actuelle. Il s’agira d’abord d’analyser les effets politiques, notamment électoraux de l’internet haut-débit, précurseur et corolaire des réseaux sociaux, avant de centrer notre revue 
de littérature sur les effets politiques de ces plateformes, et tout particulièrement de TikTok

---

## Les effets politiques, notamment électoraux, de l’Internet haut-débit


Avant l’émergence des réseaux sociaux, des études ont évoqué quatre effets principaux de l’apparition de l’internet haut-débit ; la baisse de la participation électorale, la montée du  Populisme ainsi que de l’extrême droite en Europe et la hausse de la ségrégation en ligne (online). Certaines recherches, se concentrant sur l’Allemagne (Falck, Gold and Heblich,  2014), l’Italie (Campante, Durante and Sobbrio, 2018) et le Royaume Unie (Gavazza, Nardotto  and Valletti, 2019), ont identifié un effet de substitution entre le contenu de divertissement et  la conscience politique, notamment la démobilisation électorale. Les deux premiers effets ont été identifiés dans des papiers assez similaires, exploitant le déploiement de la couverture du haut débit dans des communes au Royaume Uni (Gavazza, Nardotto and Valletti, 2019), ainsi que dans différentes régions réparties dans 116 pays (Guriev, S., Melnikov, N., & Zhuravskaya, E). Ces deux recherches ont tenté d’éliminer l’endogénéité (l’accès à Internet n’était pas attribué aléatoirement) grâce à la technique des variables instrumentale, dont l’instrument reposait sur une mesure climatique (la pluviométrie et la fréquence des éclairs). Si les variables instrumentales sont des outils efficaces pour corriger l’endogénéité, il s’agit de souligner que la limite de cette technique économétrique réside dans la faiblesse ou la force de l’instrument sélectionné. Ici, les instruments ne semblent pas fortement corrélés à la variable endogène (soit l’accès à l’internet). En effet, ces deux instruments peuvent aussi corréler avec d’autres caractéristiques socio-économiques ou géographiques (par exemple, les zones rurales et la qualité des infrastructures) qui influencent aussi la mobilisation politique. 
En outre, le papier de recherche illustrant le troisième effet de cette couverture haut-débit, soit la montée de l’extrême droite en Europe, à travers l’explosion des scores électoraux du mouvement 5 étoiles en Italie, s’est appuyé sur deux techniques économétriques complémentaires (Campante, Durante and Sobbrio, 2018). Premièrement, les variables instrumentales ont pu corriger partiellement le problème d’endogénéité (l’accès à internet) 
grâce à l’instrument utilisant la distance entre la municipalité et le central téléphonique le plus  proche (car cette distance détermine la qualité du haut débit (ADSL), ainsi que sa temporalité  d’adoption: plus la distance est grande, plus la vitesse de connexion est faible et plus le haut  débit a été adopté tard (car couts élevés)). Ensuite, afin de renforcer la robustesse de l’étude et la preuve de causalité, la double différence est efficace, apportant une dimension temporelle en comparant l’évolution avant/après introduction du haut débit entre municipalités proches et éloignées des centraux télécom. Ce cas d’étude est particulièrement intéressant pour notre étude puisque ce mouvement italien, crée par Beppe Grillo, est né grâce à Internet, sur la plateforme Meetup, s’est construit et développé virtuellement et numériquement, tout comme le parti de Câlin Georgescu. Il s’agit de candidats et partis outsiders, nés sur et par Internet et les réseaux sociaux. Finalement, le quatrième effet d’Internet, soit l’augmentation de la ségrégation idéologique des citoyens américains en ligne comparativement à la ségrégation offline, a été démontrée par les économistes Gentzkow et Shapiro (Gentzkow, M., & Shapiro, J. M. (2011)). Toutefois, entre 2004 et 2009, la ségrégation en ligne est modérée, supérieure à la plupart des médias offline mais bien inférieure aux interactions sociales. Ce papier reste limité puisqu’il ne traite pas la causalité mais seulement la corrélation. Ici, les auteurs exploitent les données d’audience et de navigation pour mesurer la polarisation des médias consommés en ligne vs hors ligne. Ils utilisent principalement des régressions, ne permettent pas de corriger l’endogénéité. En effet, l’accès à Internet et le choix des sites sont corrélés à des facteurs non observés (préférences politiques, capital culturel, niveau d’éducation) et les auteurs ne disposent pas d’un instrument  fort, ni d’une variation exogène pour isoler l’effet causal d’Internet
  

---

## Les effets politiques, notamment électoraux, des réseaux sociaux

Comme le soulignent Hunt Allcott and Matthew Gentzkow, si les démocraties ont régulièrement été impactées par les changements dans les technologies des médias, le tournant s’inscrit dans l’apparition des réseaux sociaux créant des « chambres d’échos », accentuant la polarisation politique des usagers (Allcott, H., & Gentzkow, M. (2017)). Il s’agit d’abord de se concentrer sur la littérature ayant trait au réseau social Facebook, soit le plus ancien (2004). En effet, les auteurs soulignent que les élections de 2016 aux Etats-Unis ont vu circuler une quantité importante de fake-stories sur Facebook, trois fois plus nombreuses en faveur de  D.Trump que de H.Clinton. Une seconde étude effectuée par ces mêmes auteurs, a inféré une polarisation de ce même réseau social. À la suite d’une expérience randomisée consistant en la désactivation de Facebook, chez le groupe traitement, quatre semaines avant les mid-terms de 2018, on constate une augmentation de la polarisation des opinions sur enjeux (Hunt Allcott, Luca Braghieri, Sarah Eichmeyer, and Matthew Gentzkow, 2020). En d’autres termes, les participants désactivés ont exprimé des positions moins alignées sur celles de leur parti, se rapprochant du centre. Il s’agit toutefois de rester rigoureux en soulignant l’absence de significativité pour la polarisation affective et la polarisation des croyantes factuelles. En outre, les effets du réseau social Twitter, sur les chambres d’échos et l’expression politiques, ont également été étudiés aux Etats-Unis, par une approche quasi-expérimentale (variables instrumentales) (Thomas Fujiwara Karsten Müller Carlo Schwarz). Les économistes ont exploité un choc exogène lié à l’adoption précoce de Twitter lors du festival South by Southwest (SXSW) en 2007. Leur instrument réside dans le nombre d’abonnés au compte SXSW qui ont rejoint Twitter en mars 2007 (pendant le festival). Cette méthode a été complétée par un test de robustesse, la méthode Oster (2019) pour évaluer le biais des variables non observées. Il en résulte un effet électoral certain sur les élections présidentielles de 2016 et de 2020. Une hausse de 10 % des utilisateurs Twitter dans un comté réduit la part de vote républicain (Trump) de 0,2 point en 2016 et 2020. Les auteurs expliquent cet effet positif sur le vote démocrate en soulignant le contenu pro-démocrate, à l’époque, de la plateforme. Le contexte politique ayant changé depuis lors, notamment avec l’acquision de Twitter  par Elon Musk et la réduction drastique du fact-checking, il s’agit de souligner qu’en 2025, les résultats  seraient surement différents. On comprend alors que la ligne idéologique du réseau (émanant notamment de son propriétaire), contrôlant et orientant son contenu, a des effets significatifs sur le vote.  
La limite de ces articles séminaux réside dans la concentration géographique de la recherche, cloisonnée aux Etats-Unis, raison pour laquelle il s’agit d’étendre spatialement le champ d’étude.  
En ce sens, d’autres effets politiques sont analysés, notamment la hausse des mobilisations politiques en Russie et la démocratisation du régime semi-autoritaire de Malaisie, à travers la technique des variables instrumentales. Dans ce premier papier, les économistes cherchent à savoir si l’introduction du réseau social VK en Russie, crée par un étudiant, avait eu un effet sur les mobilisations politiques dans le pays, sur la même période. Ils choisissent comme instrument le nombre d’étudiants originaires d’une ville qui ont étudié à l’Université de Saint Pétersbourg (SPbSU) dans la même cohorte que le fondateur de VK (Enikolopov, Ruben, Maria Petrova, and Ekaterina Zhuravskaya, 2011). Ils trouvent un effet causal positif entre la pénétration de ce réseau social dans les villes et le taux de manifestations. Ainsi, une augmentation de 10 % de pénétration VK entraine une hausse de 4,6 points de probabilité qu’une ville ait une protestation. Dans le second papier, le cas étudié est la Malaisie, où la coalition au pouvoir (BN) a perdu son monopole, après 40 ans de pouvoir, lors des élections de 2008. L’auteur cherche à mesurer l’impact causal de la diffusion d’Internet sur les résultats électoraux. Pour ce faire, il utilise comme instrument la distance des 433 districts étudiés, au 
Backbone des principaux ISP (Time, Fiberail, TM). Plus la distance est grande, plus le coût d’installation est élevé, constituant une variation exogène de l’offre Internet. Cette étude repose sur des mécanismes assez similaires à l’étude de Campante, F., Durante, R., et Sobbrio,F. 

---

## Les singularités du réseau social TikTok

Si TikTtok est un réseau social assez récent (2016), il dispose de plusieurs singularités, le distinguant de Facebook et Twitter dans ses effets politiques. Comme le soulignent Li et al.  (2025), TikTok crée de nouvelles opportunités de communication politique, grâce à des vidéos courtes et un esthétique singulier. Contrairement aux autres plateformes, le cœur de ce réseau 
réside dans la présence d’influenceurs et activistes, également politisés, pouvant exprimer leur  avis et leur soutien, influençant de fait leurs fans. Finalement, TikTok emploie un algorithme très sophistiqué, plus agressif et addictif (Siles et al., 2024), reposant sur le scrolling. Il est notamment très présent chez les jeunes. Il en résulte un réseau social plus politisé et influent.  Ces auteurs cherchent donc à trouver une causalité entre ce réseau et la présence plus aiguë de chambre d’échos. En se fondant techniquement sur du machine Learning non supervisé, afin de prédire le score idéologique de TikTok (entre −1 = gauche et +1 = droite), ils trouvent une présence significative de chambres d’échos, un engagement politique ainsi qu’une polarisation renforcée sur la plateforme. Les études séminales sur l’impact de TikTok dans certaines élections, notamment les dernières élections européennes (France, juillet 2024, Allemagne 2025, Géorgie 2024, Pologne 2025, Moldavie 2025, Roumanie 2024) sont encore très limitées en économie politique, réduisant de fait les possibilités de réponse à cette question de recherche. Bien que la littérature entourant Facebook et Twitter soit abondante, TikTok dispose de singularités qu’il s’agit de distinguer et étudier séparément


---

## Travaux cités

Allcott, H., & Gentzkow, M. (2017). Social media and fake news in the 2016 election.  Journal of Economic Perspectives, 31(2), 211–236. https://doi.org/10.1257/jep.31.2.211 Allcott, H., Braghieri, L., Eichmeyer, S., & Gentzkow, M. (2020). The welfare eIects of  social media. American Economic Review, 110(3), 629–676.  
https://doi.org/10.1257/aer.110.3.629 
Campante, F., Durante, R., & Sobbrio, F. (2018). Politics 2.0: The multifaceted eIect of  broadband internet on political participation. Journal of the European Economic  Association, 16(4), 1094–1136. https://doi.org/10.1093/jeea/jvx044 Digi24.ro. (2024, December 6). Klaus Iohannis a déclassifié les documents de la  dernière séance du CSAT concernant la campagne de Călin Georgescu.  https://www.digi24.ro/stiri/actualitate/politica/klaus-iohannis-a-declasificat documentele-din-ultima-sedinta-csat-despre-campania-lui-calin-georgescu-3033309
Enikolopov, R., Petrova, M., & Zhuravskaya, E. (2011). Media and political persuasion:  Evidence from Russia. American Economic Review, 101(7), 3253–3285.  https://doi.org/10.1257/aer.101.7.3253 
Falck, O., Gold, R., & Heblich, S. (2014). E-lections: Voting behavior and the Internet.  American Economic Review, 104(7), 2238–2265. https://doi.org/10.1257/aer.104.7.2238 Fujiwara, T., Müller, K., & Schwarz, C. (2024). The eIect of social media on elections:  Evidence from the United States. Journal of the European Economic Association, 22(3),  1495–1539. https://doi.org/10.1093/jeea/jvad021 
Gavazza, A., Nardotto, M., & Valletti, T. (2019). Internet and politics: Evidence from UK  local elections and local government policies. The Review of Economic Studies, 86(5),  2092–2135. https://doi.org/10.1093/restud/rdy046 
Gentzkow, M., & Shapiro, J. M. (2011). Ideological segregation online and oIline.  Quarterly Journal of Economics, 126(4), 1799–1839. https://doi.org/10.1093/qje/qjr044 Guriev, S., Melnikov, N., & Zhuravskaya, E. (2021). 3G internet and confidence in  government. The Quarterly Journal of Economics, 136(4), 2533–2613.  https://doi.org/10.1093/qje/qjab027 
Le Monde. (2024, December 6). Roumanie : la Cour constitutionnelle annule le  premier tour de l’élection présidentielle du fait de graves manipulations sur TikTok.  https://www.lemonde.fr/international/article/2024/12/06/roumanie-la-cour constitutionnelle-annule-le-premier-tour-de-l-election-presidentielle-apres-de-graves manipulations-sur-tiktok_6433720_3210.html 
Li, Y., Cheng, Z., & Gil de Zúñiga, H. (2025). TikTok’s political landscape: Examining  echo chambers and political expression dynamics. New Media & Society. Advance  online publication. https://doi.org/10.1177/14614448251339755 
Miner, L. (2015). The unintended consequences of internet diIusion: Evidence from  Malaysia. Journal of Public Economics, 132, 66–78.  
https://doi.org/10.1016/j.jpubeco.2015.01.002 
Stănescu, G. C. (2024). Fake news, bots, and influencers: The impact of social media  on Romania’s 2024 elections. Social Sciences and Education Research Review, 11(2),  361–366. 
Zhuravskaya, E., Petrova, M., & Enikolopov, R. (2020). Political eIects of the internet and social media. Annual Review of Economics, 12, 415–438.  
https://doi.org/10.1146/annurev-economics-081919-0502 
Note : utilisation de l’IA générative pour : 
